// Per-ability visual identity for the in-game ability VFX system.
// DATA-AS-CODE, projected from the Ability VFX Gallery authored specs
// (feature/ability-vfx-gallery: ability_specs.js). Regenerate with the
// projection snippet in docs/ability-vfx-ingame.md when the gallery evolves.
// Compact keys: c=color p=palette pw=power sp=sparks rg=ringScale vr=vRing
// db=debris sm=smoke bl=blood li=lightScale b={v:speed,h:headScale,j:jagged,
// co:coils,vl:volley} bo=buffOrbit lg=linger wu=windup spin fin a=archetype.
import type { AbilityVfxSpec } from './ability_vfx_core';

export const ABILITY_VFX_SPECS: Record<string, AbilityVfxSpec> = {
  heroic_strike: {
    c: '#ffa03c',
    p: 'physical',
    pw: 1,
    sp: 24,
    li: 0.6,
    bo: 'weaponGlow',
    a: 'strike',
  },
  revenge: {
    c: '#b8cbe0',
    p: 'physical',
    pw: 1.05,
    sp: 26,
    rg: 1.4,
    vr: 1,
    li: 0.9,
    lg: 1,
    a: 'strike',
  },
  battle_shout: {
    c: '#ff4636',
    p: 'blood',
    pw: 1.05,
    rg: 2,
    vr: 1,
    li: 3.2,
    bo: 'weaponGlow',
    lg: 3,
    a: 'shout',
  },
  charge: {
    c: '#e5231b',
    p: 'physical',
    pw: 1.35,
    sp: 34,
    rg: 1.8,
    vr: 1,
    db: 1,
    sm: 1,
    li: 1.5,
    bo: 'speedlines',
    lg: 1.2,
    wu: 0.2,
    a: 'dash',
  },
  thunder_clap: { c: '#8fd0ff', p: 'storm', rg: 1.3, db: 1, sm: 1, li: 0.6, wu: 0.3, a: 'nova' },
  hamstring: {
    c: '#d41f2e',
    p: 'blood',
    pw: 0.7,
    sp: 8,
    bl: 1,
    li: 0.5,
    bo: 'speedlines',
    a: 'strike',
  },
  bloodrage: {
    c: '#9e1622',
    p: 'blood',
    pw: 0.7,
    bl: 1,
    li: 1.3,
    bo: 'heartbeat',
    lg: 2,
    a: 'buff',
  },
  overpower: { c: '#e5233a', p: 'blood', sp: 22, vr: 1, li: 0.6, a: 'strike' },
  raging_gale: { c: '#dfe9f4', p: 'physical', pw: 1.1, sp: 30, li: 0.6, lg: 1, a: 'strike' },
  raised_guard: {
    c: '#9fb9d4',
    p: 'physical',
    pw: 0.75,
    sp: 8,
    vr: 1,
    li: 1.1,
    lg: 4,
    wu: 0.3,
    a: 'buff',
  },
  pummel: { c: '#dfe6ee', p: 'physical', pw: 0.7, sp: 10, vr: 1, li: 0.5, lg: 4.2, a: 'strike' },
  execute: {
    c: '#d41f2e',
    p: 'blood',
    pw: 1.6,
    sp: 60,
    rg: 1,
    vr: 1,
    db: 1,
    sm: 1,
    bl: 1,
    li: 0.8,
    wu: 0.5,
    fin: 1,
    a: 'strike',
  },
  furious_mending: {
    c: '#d8685c',
    p: 'blood',
    pw: 0.7,
    sp: 0,
    li: 1,
    bo: 'leaves',
    lg: 4,
    wu: 0.25,
    a: 'buff',
  },
  iron_resolve: {
    c: '#8b97a6',
    p: 'physical',
    pw: 0.95,
    sp: 14,
    rg: 1.2,
    db: 1,
    li: 1.2,
    bo: 'halo',
    lg: 4,
    wu: 0.4,
    a: 'buff',
  },
  slam: { c: '#dfe6ee', p: 'physical', pw: 1.1, db: 1, sm: 1, li: 0.7, wu: 1.5, a: 'strike' },
  red_harvest: { c: '#d41f2e', p: 'blood', pw: 1.25, sp: 26, bl: 1, li: 0.7, lg: 2.5, a: 'strike' },
  whirlwind: {
    c: '#dbe6f4',
    p: 'physical',
    pw: 1.2,
    sp: 34,
    rg: 1.6,
    db: 1,
    bl: 1,
    li: 0.7,
    lg: 1.5,
    wu: 0.3,
    a: 'nova',
  },
  faultline: {
    c: '#c8b89a',
    p: 'physical',
    pw: 1.2,
    sp: 14,
    rg: 2,
    db: 1,
    sm: 1,
    li: 0.8,
    lg: 1.8,
    wu: 0.35,
    a: 'nova',
  },
  heroic_leap: {
    c: '#dfe8f2',
    p: 'physical',
    pw: 1.25,
    sp: 20,
    rg: 2.2,
    db: 1,
    sm: 1,
    li: 1,
    lg: 1.2,
    wu: 0.3,
    a: 'dash',
  },
  cleave: { c: '#dfe6ee', p: 'physical', pw: 0.95, sp: 24, li: 0.6, a: 'nova' },
  rallying_cry: {
    c: '#e8eef5',
    p: 'physical',
    pw: 1.15,
    sp: 0,
    rg: 2.6,
    vr: 1,
    li: 2.6,
    bo: 'wings',
    lg: 4,
    a: 'shout',
  },
  emboldening_roar: {
    c: '#ff5a3c',
    p: 'blood',
    pw: 1.1,
    sp: 18,
    rg: 2.2,
    li: 2.2,
    bo: 'halo',
    lg: 4,
    a: 'shout',
  },
  defiant_bellow: {
    c: '#c9d6e4',
    p: 'physical',
    pw: 1.1,
    sp: 6,
    rg: 2.8,
    vr: 1,
    li: 2,
    lg: 2,
    wu: 0.3,
    a: 'shout',
  },
  battle_stance: {
    c: '#cdd9e6',
    p: 'physical',
    pw: 0.7,
    sp: 10,
    rg: 1.2,
    li: 0.9,
    bo: 'runes',
    lg: 3.5,
    wu: 0.3,
    a: 'buff',
  },
  berserker_stance: {
    c: '#e03428',
    p: 'blood',
    pw: 0.8,
    sp: 16,
    li: 0.9,
    bo: 'sparks',
    lg: 3.5,
    wu: 0.25,
    a: 'buff',
  },
  defensive_stance: {
    c: '#8fa8bd',
    p: 'physical',
    pw: 0.5,
    li: 0.5,
    bo: 'plates',
    lg: 2,
    wu: 0.4,
    a: 'buff',
  },
  demoralizing_shout: {
    c: '#6b5a8c',
    p: 'shadow',
    pw: 1.15,
    sp: 0,
    rg: 2.6,
    sm: 1,
    li: 2,
    lg: 2,
    wu: 0.3,
    a: 'shout',
  },
  intimidating_shout: {
    c: '#8a6ab8',
    p: 'shadow',
    pw: 1.2,
    sp: 0,
    rg: 2.4,
    sm: 1,
    li: 1.8,
    lg: 2.5,
    wu: 0.3,
    a: 'shout',
  },
  sunder_armor: { c: '#dfe6ee', p: 'physical', pw: 0.8, sp: 45, db: 1, li: 0.6, a: 'strike' },
  taunt: { c: '#dfe6ee', p: 'physical', pw: 0.85, sp: 10, rg: 1.8, vr: 1, li: 2.6, a: 'shout' },
  measured_fury: {
    c: '#aab8c6',
    p: 'physical',
    pw: 0.55,
    sp: 0,
    li: 0.5,
    lg: 2.5,
    wu: 0.2,
    a: 'buff',
  },
  seasoned_soldier: {
    c: '#c2cfdb',
    p: 'physical',
    pw: 0.6,
    sp: 10,
    li: 0.7,
    lg: 2.5,
    wu: 0.2,
    a: 'buff',
  },
  sudden_death: {
    c: '#d4dde6',
    p: 'physical',
    pw: 0.62,
    sp: 2,
    vr: 1,
    li: 0.9,
    lg: 2.5,
    wu: 0.2,
    a: 'buff',
  },
  diabolical_twinstrike: {
    c: '#c8322a',
    p: 'blood',
    pw: 0.58,
    sp: 12,
    li: 0.7,
    lg: 2.5,
    wu: 0.2,
    a: 'buff',
  },
  cleaving_blows: {
    c: '#b03040',
    p: 'blood',
    pw: 0.56,
    sp: 8,
    li: 0.6,
    lg: 2.5,
    wu: 0.2,
    a: 'buff',
  },
  breachmaker: {
    c: '#e0a05a',
    p: 'physical',
    pw: 1.25,
    sp: 30,
    rg: 1.3,
    vr: 1,
    db: 1,
    li: 0.9,
    lg: 2.5,
    wu: 0.35,
    a: 'strike',
  },
  sweeping_strikes: {
    c: '#dbe6f4',
    p: 'physical',
    pw: 0.9,
    sp: 12,
    li: 0.8,
    bo: 'sparks',
    lg: 4,
    wu: 0.3,
    a: 'buff',
  },
  deep_wounds: {
    c: '#9e1622',
    p: 'blood',
    pw: 0.55,
    sp: 0,
    bl: 1,
    li: 0.4,
    lg: 3,
    wu: 0.2,
    a: 'buff',
  },
  enrage_passive: {
    c: '#ff2a14',
    p: 'blood',
    pw: 0.65,
    sp: 14,
    li: 1.1,
    lg: 2.5,
    wu: 0.2,
    a: 'buff',
  },
  mortal_strike: {
    c: '#e5e9f0',
    p: 'physical',
    pw: 1.3,
    sp: 40,
    vr: 1,
    db: 1,
    bl: 1,
    li: 0.8,
    lg: 1.5,
    wu: 0.4,
    a: 'strike',
  },
  bloodthirst: {
    c: '#c41022',
    p: 'blood',
    pw: 1.2,
    sp: 34,
    rg: 1.4,
    vr: 1,
    db: 1,
    bl: 1,
    li: 0.6,
    lg: 1,
    a: 'strike',
  },
  shield_slam: {
    c: '#bcd0e8',
    p: 'physical',
    pw: 1.2,
    sp: 16,
    rg: 1.6,
    vr: 1,
    db: 1,
    sm: 1,
    li: 1.4,
    lg: 1,
    wu: 0.3,
    a: 'strike',
  },
  berserker_rage: {
    c: '#ff2a14',
    p: 'blood',
    pw: 1.15,
    sp: 20,
    rg: 1.8,
    vr: 1,
    bl: 1,
    li: 2.6,
    bo: 'heartbeat',
    lg: 3.5,
    wu: 0.3,
    a: 'buff',
  },
  storm_bolt: {
    c: '#cfdae6',
    p: 'physical',
    pw: 1.1,
    sp: 24,
    rg: 1.2,
    vr: 1,
    li: 0.9,
    b: { v: 22, h: 1.1 },
    lg: 1.5,
    wu: 0.3,
    a: 'bolt',
  },
  bladestorm: {
    c: '#eef2f8',
    p: 'physical',
    pw: 1.5,
    sp: 44,
    rg: 2.2,
    vr: 1,
    db: 1,
    li: 1,
    bo: 'sparks',
    lg: 4,
    wu: 0.5,
    spin: 1,
    a: 'nova',
  },
  victory_rush: { c: '#dfe8dd', p: 'physical', pw: 1.15, sp: 18, li: 1.4, lg: 1.5, a: 'strike' },
  piercing_howl: {
    c: '#9fb4c8',
    p: 'physical',
    pw: 1.1,
    sp: 0,
    rg: 3,
    sm: 1,
    li: 1.6,
    lg: 2,
    a: 'shout',
  },
  die_by_sword: {
    c: '#d4dde8',
    p: 'physical',
    pw: 0.95,
    sp: 16,
    vr: 1,
    li: 1,
    bo: 'speedlines',
    lg: 4,
    wu: 0.3,
    a: 'buff',
  },
  recklessness: {
    c: '#ff3820',
    p: 'blood',
    pw: 1.2,
    sp: 22,
    li: 1.4,
    bo: 'heartbeat',
    lg: 4,
    wu: 0.25,
    a: 'buff',
  },
  avatar: {
    c: '#d8dce2',
    p: 'physical',
    pw: 1.5,
    sp: 16,
    rg: 1.8,
    db: 1,
    sm: 1,
    li: 1.6,
    bo: 'plates',
    lg: 4,
    wu: 0.5,
    a: 'buff',
  },
  sanguine_aura: {
    c: '#8e1220',
    p: 'blood',
    pw: 1.1,
    sp: 12,
    rg: 2,
    bl: 1,
    li: 1.8,
    bo: 'weaponGlow',
    lg: 4,
    wu: 0.3,
    a: 'buff',
  },
  fireball: {
    c: '#ff7a2a',
    p: 'fire',
    sp: 36,
    rg: 1,
    db: 1,
    sm: 1,
    b: { v: 17, h: 1.4 },
    lg: 3,
    wu: 1.7,
    a: 'bolt',
  },
  frost_armor: { c: '#bfeaff', p: 'frost', pw: 0.7, bo: 'sparks', lg: 2, a: 'buff' },
  arcane_intellect: { c: '#c9a6ff', p: 'arcane', pw: 0.65, bo: 'halo', lg: 2, a: 'buff' },
  frostbolt: {
    c: '#e8f6ff',
    p: 'frost',
    pw: 0.95,
    sp: 18,
    vr: 1,
    db: 1,
    b: { v: 20, h: 1.1, co: 1 },
    lg: 2,
    a: 'bolt',
  },
  conjure_water: { c: '#aee7ff', p: 'frost', pw: 0.6, lg: 1.5, a: 'buff' },
  blink: { c: '#c9a6ff', p: 'arcane', pw: 0.9, sp: 14, vr: 1, sm: 1, li: 1.2, lg: 0.9, a: 'dash' },
  ice_block: { c: '#dff4ff', p: 'frost', pw: 1.05, sp: 0, rg: 1.1, db: 1, li: 1, lg: 6, a: 'buff' },
  ignition: { c: '#ff6a3c', p: 'fire', pw: 0.6, sp: 10, sm: 1, li: 0.7, lg: 3, wu: 0.2, a: 'buff' },
  hot_streak: { c: '#ff8438', p: 'fire', pw: 0.62, sp: 6, li: 0.9, lg: 3, wu: 0.2, a: 'buff' },
  blazing_barrier: {
    c: '#ff8c3c',
    p: 'fire',
    sp: 18,
    sm: 1,
    li: 1.6,
    bo: 'runes',
    lg: 4,
    wu: 0.3,
    a: 'buff',
  },
  meteor: {
    c: '#ff6a2a',
    p: 'fire',
    pw: 1.55,
    sp: 60,
    rg: 2.5,
    db: 1,
    sm: 1,
    li: 1.5,
    lg: 3.5,
    wu: 2.2,
    a: 'burst',
  },
  combustion: {
    c: '#ff7a2a',
    p: 'fire',
    pw: 1.3,
    sp: 42,
    sm: 1,
    li: 2.8,
    bo: 'sparks',
    lg: 4,
    wu: 0.3,
    a: 'buff',
  },
  summon_water_elemental: { c: '#aee7ff', p: 'frost', sp: 12, li: 1.2, lg: 3, wu: 2, a: 'summon' },
  ice_lance: {
    c: '#dff6ff',
    p: 'frost',
    pw: 0.95,
    sp: 16,
    vr: 1,
    db: 1,
    li: 0.8,
    b: { v: 32, h: 0.85 },
    lg: 1.5,
    a: 'bolt',
  },
  fingers_of_frost: {
    c: '#9fe0ff',
    p: 'frost',
    pw: 0.58,
    sp: 2,
    vr: 1,
    li: 0.8,
    lg: 3,
    wu: 0.2,
    a: 'buff',
  },
  brain_freeze: {
    c: '#d8f4ff',
    p: 'frost',
    pw: 0.56,
    sp: 8,
    db: 1,
    li: 0.7,
    lg: 3,
    wu: 0.2,
    a: 'buff',
  },
  shatter: { c: '#7fc8e8', p: 'frost', pw: 0.6, sp: 0, db: 1, li: 0.6, lg: 3, wu: 0.2, a: 'buff' },
  conjure_food: {
    c: '#ffcf8a',
    p: 'arcane',
    pw: 0.6,
    sp: 6,
    sm: 1,
    li: 0.5,
    lg: 1.5,
    wu: 2,
    a: 'buff',
  },
  counterspell: { c: '#c86bff', p: 'arcane', pw: 0.7, sp: 18, vr: 1, li: 0.6, a: 'burst' },
  fire_blast: { c: '#ffd23e', p: 'fire', pw: 1.05, sp: 44, vr: 1, a: 'burst' },
  arcane_missiles: {
    c: '#c86bff',
    p: 'arcane',
    pw: 0.95,
    sp: 16,
    b: { v: 22, h: 0.75, vl: 4 },
    a: 'bolt',
  },
  flurry: {
    c: '#bfeaff',
    p: 'frost',
    sp: 12,
    db: 1,
    li: 0.7,
    b: { h: 0.75, vl: 3 },
    lg: 2,
    wu: 1.4,
    a: 'bolt',
  },
  polymorph: { c: '#c86bff', p: 'arcane', pw: 0.85, lg: 4, a: 'cc' },
  frost_nova: { c: '#7fd4ff', p: 'frost', pw: 1.35, sp: 26, db: 1, lg: 3.5, fin: 1, a: 'nova' },
  frozen_orb: {
    c: '#9fd8f0',
    p: 'frost',
    pw: 1.2,
    sp: 30,
    rg: 2,
    db: 1,
    li: 1.1,
    b: { v: 7, h: 2.4 },
    lg: 4,
    wu: 0.4,
    a: 'bolt',
  },
  blizzard: { c: '#bfe4f6', p: 'frost', pw: 1.1, sp: 22, sm: 1, li: 0.8, lg: 5, wu: 2, a: 'dot' },
  icy_veins: {
    c: '#8fe6ff',
    p: 'frost',
    pw: 1.2,
    sp: 0,
    vr: 1,
    db: 1,
    li: 1.9,
    bo: 'halo',
    lg: 4,
    wu: 0.4,
    a: 'buff',
  },
  glacial_spike: {
    c: '#8fd0e8',
    p: 'frost',
    pw: 1.45,
    sp: 44,
    rg: 1.4,
    vr: 1,
    db: 1,
    li: 1.2,
    b: { v: 16, h: 2 },
    lg: 3,
    wu: 2.5,
    a: 'bolt',
  },
  glacial_front: {
    c: '#a8dcf0',
    p: 'frost',
    pw: 1.25,
    sp: 26,
    rg: 2.2,
    db: 1,
    li: 1,
    lg: 2.5,
    wu: 2.4,
    a: 'nova',
  },
  dragons_breath: {
    c: '#ff9038',
    p: 'fire',
    pw: 1.3,
    sp: 36,
    rg: 1.6,
    sm: 1,
    li: 1.2,
    lg: 2.5,
    wu: 2.4,
    a: 'nova',
  },
  arcane_explosion: { c: '#c86bff', p: 'arcane', sp: 24, rg: 2, wu: 0.25, a: 'nova' },
  scorch: { c: '#b83a10', p: 'fire', pw: 0.85, sp: 10, sm: 1, a: 'burst' },
  ice_barrier: { c: '#58b8dc', p: 'frost', pw: 1.1, bo: 'plates', lg: 4, a: 'buff' },
  pyroblast: {
    c: '#ff7a2a',
    p: 'fire',
    pw: 1.5,
    sp: 50,
    rg: 2,
    vr: 1,
    db: 1,
    sm: 1,
    li: 0.9,
    b: { v: 20, h: 1.8 },
    lg: 4,
    wu: 2.5,
    a: 'bolt',
  },
  flamestrike: {
    c: '#ff7a2a',
    p: 'fire',
    pw: 1.15,
    sp: 30,
    rg: 2,
    sm: 1,
    li: 0.8,
    lg: 2.5,
    a: 'nova',
  },
  temporal_barrier: {
    c: '#7de8dc',
    p: 'arcane',
    pw: 0.95,
    sp: 8,
    li: 1.4,
    bo: 'plates',
    lg: 4,
    a: 'buff',
  },
  temporal_echo: { c: '#7de8dc', p: 'arcane', pw: 0.8, sp: 6, vr: 1, li: 1.2, lg: 4, a: 'heal' },
  arcane_surge: {
    c: '#c86bff',
    p: 'arcane',
    pw: 1.15,
    sp: 28,
    rg: 1.6,
    vr: 1,
    li: 1.2,
    b: { v: 28, h: 1.15, co: 1 },
    lg: 2,
    wu: 2,
    a: 'bolt',
  },
  temporal_cascade: { c: '#9ff0e6', p: 'arcane', sp: 10, rg: 2, li: 1.5, lg: 3, wu: 2, a: 'heal' },
  temporal_reversal: {
    c: '#b0f4ea',
    p: 'arcane',
    pw: 1.15,
    sp: 12,
    rg: 1.6,
    vr: 1,
    li: 2,
    lg: 3.5,
    wu: 2,
    a: 'heal',
  },
  collective_reversal: {
    c: '#c2f8f0',
    p: 'arcane',
    pw: 1.2,
    sp: 16,
    rg: 2.8,
    li: 2.2,
    lg: 4,
    wu: 2.5,
    a: 'heal',
  },
  temporal_rewind: {
    c: '#7de8dc',
    p: 'arcane',
    sp: 0,
    rg: 2.8,
    li: 2,
    lg: 2.5,
    wu: 0.3,
    a: 'nova',
  },
  temporal_hourglass: {
    c: '#8ff0e4',
    p: 'arcane',
    pw: 0.95,
    sp: 10,
    vr: 1,
    li: 1.3,
    lg: 4.5,
    wu: 0.4,
    a: 'cc',
  },
  temporal_acceleration: {
    c: '#6fe0d8',
    p: 'arcane',
    pw: 1.05,
    sp: 12,
    rg: 1.8,
    li: 1.8,
    bo: 'leaves',
    lg: 4.5,
    a: 'buff',
  },
  perfect_moment: {
    c: '#9ff0e6',
    p: 'arcane',
    pw: 0.95,
    sp: 14,
    vr: 1,
    li: 1.6,
    bo: 'heartbeat',
    lg: 4,
    a: 'buff',
  },
  fireball_form: {
    c: '#ff7a2a',
    p: 'fire',
    pw: 1.1,
    sp: 24,
    sm: 1,
    li: 1.8,
    bo: 'speedlines',
    lg: 4,
    wu: 1.8,
    a: 'buff',
  },
  temporal_mend: { c: '#8ff0e4', p: 'arcane', pw: 0.85, sp: 8, li: 1.4, lg: 2.5, wu: 2, a: 'heal' },
  arcane_power: {
    c: '#c86bff',
    p: 'arcane',
    pw: 1.4,
    sp: 30,
    rg: 2,
    vr: 1,
    li: 3.4,
    bo: 'runes',
    lg: 4,
    wu: 0.5,
    a: 'buff',
  },
  evocation: { c: '#c9a6ff', p: 'arcane', sp: 20, li: 1.6, lg: 4, wu: 0.4, a: 'buff' },
  presence_of_mind: {
    c: '#d0aaff',
    p: 'arcane',
    pw: 0.85,
    sp: 12,
    vr: 1,
    li: 1.2,
    bo: 'speedlines',
    lg: 4,
    a: 'buff',
  },
  ice_floes: {
    c: '#bfeaff',
    p: 'frost',
    pw: 0.75,
    sp: 8,
    db: 1,
    li: 0.8,
    bo: 'runes',
    lg: 4,
    a: 'buff',
  },
  greater_invisibility: {
    c: '#d0c2f0',
    p: 'arcane',
    pw: 0.8,
    sp: 0,
    sm: 1,
    li: 0.6,
    lg: 4,
    a: 'buff',
  },
  rings_of_frost: {
    c: '#a8d8ec',
    p: 'frost',
    pw: 1.05,
    sp: 12,
    rg: 2.6,
    li: 0.9,
    lg: 4,
    wu: 1.4,
    a: 'nova',
  },
  cold_snap: {
    c: '#dff4ff',
    p: 'frost',
    pw: 0.85,
    sp: 20,
    vr: 1,
    db: 1,
    li: 1.2,
    lg: 1.5,
    a: 'buff',
  },
  mass_barrier: {
    c: '#bfe8f8',
    p: 'frost',
    pw: 1.05,
    sp: 8,
    rg: 2.8,
    li: 1.8,
    lg: 4,
    wu: 0.3,
    a: 'buff',
  },
  overload: { c: '#d08cff', p: 'arcane', sp: 26, li: 1.4, bo: 'weaponGlow', lg: 4, a: 'buff' },
  power_echo: { c: '#b892e8', p: 'arcane', pw: 0.8, sp: 10, vr: 1, li: 1.1, lg: 3, a: 'buff' },
  rune_of_power: {
    c: '#c86bff',
    p: 'arcane',
    sp: 14,
    rg: 1.6,
    li: 1.5,
    lg: 5,
    wu: 1.4,
    a: 'burst',
  },
  sinister_strike: { c: '#dfe6ee', p: 'physical', pw: 0.85, sp: 14, a: 'strike' },
  eviscerate: {
    c: '#d41f2e',
    p: 'blood',
    pw: 1.45,
    sp: 36,
    db: 1,
    bl: 1,
    li: 0.5,
    wu: 0.2,
    fin: 1,
    a: 'strike',
  },
  garrote: {
    c: '#d41f2e',
    p: 'blood',
    pw: 0.8,
    sp: 0,
    vr: 1,
    sm: 1,
    bl: 1,
    li: 0.3,
    lg: 3.5,
    a: 'strike',
  },
  backstab: { c: '#8a6ab8', p: 'shadow', sp: 8, bl: 1, li: 0.6, a: 'strike' },
  gouge: { c: '#dfe6ee', p: 'physical', pw: 0.85, sp: 12, a: 'strike' },
  cheap_shot: { c: '#dfe6ee', p: 'physical', pw: 0.9, sp: 6, sm: 1, li: 0.3, lg: 2, a: 'strike' },
  evasion: { c: '#9fb8d8', p: 'physical', bo: 'wings', lg: 4, a: 'buff' },
  sap: { c: '#dfe6ee', p: 'physical', pw: 0.7, sp: 4, sm: 1, li: 0.3, lg: 4, a: 'cc' },
  slice_and_dice: { c: '#e8c860', p: 'physical', pw: 1.05, bo: 'sparks', lg: 4, a: 'buff' },
  sprint: {
    c: '#cdd9e6',
    p: 'physical',
    pw: 0.7,
    sp: 0,
    sm: 1,
    bo: 'speedlines',
    lg: 2,
    a: 'buff',
  },
  crippling_poison: {
    c: '#c8ff3c',
    p: 'venom',
    pw: 0.8,
    sp: 6,
    sm: 1,
    li: 0.4,
    lg: 3,
    a: 'strike',
  },
  kidney_shot: { c: '#d41f2e', p: 'blood', pw: 1.2, sp: 20, vr: 1, a: 'strike' },
  expose_armor: {
    c: '#dfe6ee',
    p: 'physical',
    pw: 1.05,
    sp: 34,
    vr: 1,
    db: 1,
    li: 0.6,
    a: 'strike',
  },
  ambush: {
    c: '#2e2640',
    p: 'shadow',
    pw: 1.4,
    sp: 18,
    sm: 1,
    bl: 1,
    li: 0.3,
    lg: 0.6,
    wu: 0.5,
    a: 'strike',
  },
  rupture: { c: '#d41f2e', p: 'blood', pw: 1.15, sp: 0, bl: 1, li: 0.4, lg: 4, a: 'dot' },
  vanish: {
    c: '#241f33',
    p: 'shadow',
    pw: 0.9,
    sp: 0,
    rg: 1.4,
    sm: 1,
    li: 0.3,
    lg: 2.5,
    a: 'buff',
  },
  instant_poison: {
    c: '#8fd455',
    p: 'venom',
    pw: 0.7,
    sp: 10,
    li: 0.5,
    bo: 'weaponGlow',
    lg: 3,
    wu: 0.4,
    a: 'buff',
  },
  adrenaline_rush: {
    c: '#e03a2e',
    p: 'blood',
    pw: 1.25,
    li: 0.6,
    bo: 'heartbeat',
    lg: 3.5,
    a: 'buff',
  },
  deadly_poison: {
    c: '#c8ff3c',
    p: 'venom',
    pw: 0.85,
    sp: 0,
    sm: 1,
    li: 0.3,
    lg: 4,
    wu: 0.6,
    a: 'buff',
  },
  // Dirt Toss: khaki - the color IS the dirt (the dust cone, the poof, the
  // windup all ride it), not the old pale steel
  blind: { c: '#c2b280', p: 'physical', pw: 0.8, sp: 0, db: 1, sm: 1, li: 0.3, lg: 4, a: 'cc' },
  stealth: { c: '#3a3450', p: 'shadow', pw: 0.5, sp: 0, sm: 1, li: 0.3, lg: 2, a: 'buff' },
  kick: { c: '#dfe6ee', p: 'physical', pw: 0.7, sp: 12, vr: 1, li: 0.5, a: 'strike' },
  cold_blood: {
    c: '#bfeaff',
    p: 'frost',
    pw: 0.95,
    sp: 12,
    vr: 1,
    db: 1,
    li: 1.2,
    lg: 3.5,
    wu: 0.5,
    a: 'buff',
  },
  blade_flurry: {
    c: '#dfe9f4',
    p: 'physical',
    pw: 1.05,
    sp: 22,
    vr: 1,
    li: 0.7,
    bo: 'plates',
    lg: 3.5,
    wu: 0.3,
    a: 'buff',
  },
  hemorrhage: {
    c: '#d41f2e',
    p: 'blood',
    pw: 1.2,
    sp: 14,
    vr: 1,
    bl: 1,
    li: 0.7,
    lg: 3.5,
    wu: 0.3,
    a: 'strike',
  },
  smoke_screen: {
    c: '#9aa4ae',
    p: 'physical',
    pw: 0.75,
    sp: 0,
    rg: 1.4,
    sm: 1,
    li: 0.5,
    lg: 4,
    a: 'buff',
  },
  preparation: { c: '#c8d2dc', p: 'physical', pw: 0.6, sp: 8, vr: 1, li: 0.8, lg: 2, a: 'buff' },
  ghostly_strike: { c: '#b4a8e0', p: 'moon', sp: 14, vr: 1, li: 0.8, lg: 3, a: 'strike' },
  cloak_of_shadows: { c: '#7e6ba8', p: 'shadow', pw: 0.9, sp: 0, sm: 1, li: 0.7, lg: 4, a: 'buff' },
  shadowstep: { c: '#7a6a9e', p: 'shadow', pw: 0.85, sp: 8, sm: 1, li: 0.8, lg: 0.8, a: 'dash' },
  seal_of_righteousness: {
    c: '#ffd76a',
    p: 'gold',
    pw: 0.8,
    bo: 'weaponGlow',
    lg: 3,
    wu: 0.5,
    a: 'buff',
  },
  holy_light: { c: '#ffd970', p: 'holy', li: 0.8, wu: 2.5, a: 'heal' },
  devotion_aura: { c: '#f7edc6', p: 'holy', pw: 0.6, bo: 'halo', lg: 2, a: 'buff' },
  blessing_of_might: {
    c: '#d4941e',
    p: 'gold',
    pw: 0.7,
    sp: 14,
    li: 1.3,
    bo: 'wings',
    lg: 2,
    a: 'buff',
  },
  divine_protection: { c: '#ffe9a8', p: 'holy', pw: 0.9, lg: 3.5, a: 'buff' },
  hammer_of_justice: { c: '#ffd970', p: 'gold', sp: 18, vr: 1, db: 1, li: 0.9, lg: 3, a: 'cc' },
  lay_on_hands: { c: '#ffd970', p: 'holy', pw: 1.6, db: 1, li: 0.7, wu: 0.8, a: 'heal' },
  holy_taunt: { c: '#ffdf80', p: 'gold', pw: 0.8, sp: 10, vr: 1, li: 0.9, lg: 1.5, a: 'shout' },
  flash_of_light: { c: '#ffd970', p: 'holy', pw: 0.8, sp: 12, vr: 1, li: 1.1, wu: 1.5, a: 'heal' },
  exorcism: { c: '#ffd970', p: 'holy', pw: 1.1, a: 'burst' },
  consecration: { c: '#ffd970', p: 'gold', sp: 18, li: 0.6, lg: 4, wu: 0.5, a: 'nova' },
  righteous_fury: {
    c: '#ff7a2a',
    p: 'fire',
    pw: 0.75,
    bo: 'heartbeat',
    lg: 2.5,
    wu: 0.4,
    a: 'buff',
  },
  retribution_aura: {
    c: '#ffb347',
    p: 'gold',
    pw: 0.65,
    sp: 12,
    li: 0.5,
    bo: 'sparks',
    lg: 3,
    a: 'buff',
  },
  rebuke: { c: '#dfe6ee', p: 'physical', pw: 0.7, sp: 12, vr: 1, li: 0.5, a: 'strike' },
  sacred_bulwark: {
    c: '#d8e4f2',
    p: 'gold',
    pw: 1.25,
    sp: 20,
    rg: 1.4,
    vr: 1,
    li: 1.1,
    bo: 'plates',
    lg: 4,
    wu: 0.8,
    a: 'buff',
  },
  crusader_strike: {
    c: '#ffcf5a',
    p: 'gold',
    pw: 1.35,
    sp: 40,
    vr: 1,
    li: 1.5,
    lg: 0.6,
    wu: 0.4,
    a: 'strike',
  },
  holy_shock: {
    c: '#fff2cc',
    p: 'holy',
    pw: 1.35,
    sp: 36,
    rg: 2,
    vr: 1,
    li: 1.8,
    lg: 1.5,
    wu: 0.3,
    a: 'burst',
  },
  holy_shield: {
    c: '#fff0c0',
    p: 'holy',
    pw: 1.3,
    sp: 30,
    rg: 2,
    vr: 1,
    li: 1.4,
    b: { v: 22, h: 1.7 },
    lg: 1.5,
    wu: 0.3,
    a: 'bolt',
  },
  avenging_wrath: {
    c: '#ffdf8a',
    p: 'holy',
    pw: 1.35,
    sp: 20,
    rg: 1.8,
    li: 2.4,
    bo: 'wings',
    lg: 4,
    wu: 0.4,
    a: 'buff',
  },
  hammer_of_wrath: {
    c: '#f4d060',
    p: 'holy',
    pw: 1.3,
    sp: 30,
    rg: 1.4,
    vr: 1,
    li: 1.4,
    b: { h: 1.3 },
    lg: 1.5,
    a: 'bolt',
  },
  raptor_strike: {
    c: '#e03a24',
    p: 'physical',
    pw: 1.15,
    sp: 26,
    vr: 1,
    db: 1,
    bl: 1,
    li: 0.6,
    wu: 0.5,
    a: 'strike',
  },
  aspect_of_the_hawk: {
    c: '#8fc6ff',
    p: 'storm',
    sp: 14,
    rg: 1.6,
    vr: 1,
    li: 1.6,
    bo: 'wings',
    lg: 3.5,
    wu: 0.3,
    a: 'buff',
  },
  serpent_sting: { c: '#c8ff3c', p: 'venom', pw: 0.85, sp: 8, db: 1, li: 0.5, lg: 4, a: 'dot' },
  arcane_shot: { c: '#c86bff', p: 'arcane', pw: 0.95, b: { v: 40, h: 0.7 }, a: 'bolt' },
  concussive_shot: {
    c: '#dfe6ee',
    p: 'physical',
    pw: 0.8,
    sp: 0,
    rg: 1,
    vr: 1,
    db: 1,
    sm: 1,
    li: 0.6,
    b: { v: 30, h: 0.9 },
    lg: 2,
    a: 'bolt',
  },
  mongoose_bite: { c: '#a4ff4f', p: 'physical', pw: 0.95, sp: 18, vr: 1, li: 0.6, a: 'strike' },
  wing_clip: {
    c: '#dfe6ee',
    p: 'physical',
    pw: 0.7,
    sp: 6,
    db: 1,
    sm: 1,
    bl: 1,
    li: 0.4,
    lg: 2,
    a: 'strike',
  },
  tame_beast: {
    c: '#8cd07a',
    p: 'nature',
    pw: 0.8,
    sp: 8,
    sm: 1,
    li: 0.6,
    lg: 3,
    wu: 2.5,
    a: 'summon',
  },
  dismiss_pet: { c: '#86cfae', p: 'nature', pw: 0.5, lg: 1.5, a: 'buff' },
  revive_pet: { c: '#8cd07a', p: 'nature', pw: 0.75, wu: 1.5, a: 'summon' },
  aspect_of_the_monkey: {
    c: '#8fd455',
    p: 'physical',
    pw: 0.7,
    sp: 22,
    vr: 1,
    li: 1.2,
    bo: 'sparks',
    lg: 3,
    a: 'buff',
  },
  aspect_of_the_cheetah: {
    c: '#e8a34c',
    p: 'physical',
    pw: 0.8,
    sp: 10,
    rg: 1.4,
    db: 1,
    sm: 1,
    li: 1.4,
    bo: 'speedlines',
    lg: 3,
    wu: 0.3,
    a: 'buff',
  },
  aimed_shot: {
    c: '#dfe6ee',
    p: 'physical',
    pw: 1.45,
    sp: 48,
    rg: 1,
    vr: 1,
    db: 1,
    li: 0.7,
    b: { v: 48 },
    wu: 2.5,
    fin: 1,
    a: 'bolt',
  },
  rapid_fire: {
    c: '#ff6242',
    p: 'physical',
    pw: 0.9,
    sp: 10,
    li: 0.5,
    b: { v: 45, h: 0.6, vl: 5 },
    bo: 'heartbeat',
    lg: 3,
    wu: 0.4,
    a: 'buff',
  },
  volley: {
    c: '#dfe6ee',
    p: 'physical',
    pw: 1.05,
    sp: 16,
    rg: 1.2,
    db: 1,
    sm: 1,
    li: 0.4,
    lg: 3,
    wu: 0.4,
    a: 'nova',
  },
  counter_shot: { c: '#dfe6ee', p: 'physical', pw: 0.7, sp: 14, vr: 1, li: 0.5, a: 'burst' },
  bestial_wrath: {
    c: '#ff2e1a',
    p: 'blood',
    pw: 1.35,
    sp: 24,
    rg: 2,
    vr: 1,
    li: 2.6,
    bo: 'heartbeat',
    lg: 3.5,
    wu: 0.4,
    a: 'buff',
  },
  trueshot_aura: {
    c: '#9fd0ff',
    p: 'storm',
    pw: 1.05,
    sp: 20,
    rg: 3,
    vr: 1,
    li: 2.2,
    bo: 'sparks',
    lg: 2.5,
    wu: 0.3,
    a: 'buff',
  },
  wyvern_sting: { c: '#c8ff3c', p: 'venom', pw: 1.15, sp: 14, sm: 1, li: 0.5, lg: 4, a: 'cc' },
  startle_shot: {
    c: '#c8d4b8',
    p: 'physical',
    pw: 0.8,
    sp: 6,
    vr: 1,
    sm: 1,
    li: 0.7,
    b: { v: 30, h: 0.8 },
    lg: 2,
    a: 'bolt',
  },
  frost_trap: {
    c: '#a8e0e8',
    p: 'frost',
    pw: 0.9,
    sp: 14,
    rg: 1.3,
    db: 1,
    li: 0.8,
    lg: 4,
    wu: 0.3,
    a: 'burst',
  },
  multi_shot: {
    c: '#d8e0c8',
    p: 'physical',
    pw: 1.05,
    sp: 18,
    li: 0.7,
    b: { v: 30, h: 0.7, vl: 3 },
    lg: 1,
    a: 'bolt',
  },
  deterrence: {
    c: '#c2b8a0',
    p: 'physical',
    pw: 0.9,
    sp: 10,
    vr: 1,
    li: 0.9,
    bo: 'plates',
    lg: 4,
    wu: 0.3,
    a: 'buff',
  },
  aspect_of_the_wild: {
    c: '#8cd07a',
    p: 'nature',
    pw: 1.1,
    sp: 12,
    rg: 2,
    li: 1.5,
    bo: 'leaves',
    lg: 4,
    a: 'buff',
  },
  feed_pet: { c: '#8cd07a', p: 'nature', pw: 0.6, sp: 12, vr: 1, li: 0.6, lg: 2.5, a: 'summon' },
  abandon_pet: { c: '#8cd07a', p: 'nature', pw: 0.55, sp: 0, sm: 1, li: 0.4, lg: 2.2, a: 'summon' },
  smite: { c: '#ffd970', p: 'holy', pw: 0.9, sp: 26, rg: 1, li: 0.5, a: 'burst' },
  lesser_heal: { c: '#f2f6ff', p: 'holy', pw: 0.65, a: 'heal' },
  power_word_fortitude: { c: '#ffd9a0', p: 'holy', pw: 0.6, bo: 'heartbeat', lg: 2, a: 'buff' },
  shadow_word_pain: { c: '#8a6ab8', p: 'shadow', pw: 0.85, sp: 4, sm: 1, li: 0.6, lg: 4, a: 'dot' },
  power_word_shield: { c: '#eef4ff', p: 'holy', pw: 0.95, bo: 'plates', lg: 4, a: 'buff' },
  renew: { c: '#f2f6ff', p: 'holy', pw: 0.6, lg: 4, a: 'heal' },
  mind_blast: {
    c: '#8a6ab8',
    p: 'shadow',
    pw: 1.3,
    sp: 20,
    rg: 1,
    vr: 1,
    sm: 1,
    fin: 1,
    a: 'burst',
  },
  heal: { c: '#f2f6ff', p: 'holy', a: 'heal' },
  mind_flay: { c: '#8a6ab8', p: 'shadow', pw: 1.05, sp: 8, sm: 1, li: 1.3, a: 'beam' },
  flash_heal: { c: '#f2f6ff', p: 'holy', pw: 0.8, sp: 18, vr: 1, li: 1.2, a: 'heal' },
  power_infusion: {
    c: '#ffe08a',
    p: 'holy',
    pw: 1.05,
    sp: 18,
    vr: 1,
    li: 1.9,
    bo: 'halo',
    lg: 3,
    wu: 0.3,
    a: 'buff',
  },
  holy_nova: {
    c: '#fff2c8',
    p: 'holy',
    pw: 1.35,
    sp: 32,
    rg: 2.6,
    vr: 1,
    li: 2.4,
    lg: 2.5,
    wu: 0.3,
    a: 'nova',
  },
  shadowform: {
    c: '#6b4fbf',
    p: 'shadow',
    pw: 1.15,
    sp: 0,
    sm: 1,
    li: 1.2,
    lg: 3,
    wu: 0.5,
    a: 'buff',
  },
  silence: { c: '#6b5a8c', p: 'shadow', pw: 0.85, sp: 0, vr: 1, sm: 1, li: 0.8, lg: 2, a: 'burst' },
  psychic_scream: {
    c: '#9a7ec8',
    p: 'shadow',
    pw: 1.1,
    sp: 0,
    rg: 2.2,
    vr: 1,
    li: 1.8,
    lg: 2,
    a: 'shout',
  },
  inner_focus: {
    c: '#f2ecd8',
    p: 'holy',
    pw: 0.6,
    sp: 4,
    li: 0.8,
    bo: 'runes',
    lg: 4,
    wu: 0.25,
    a: 'buff',
  },
  desperate_prayer: { c: '#ffe8b0', p: 'holy', pw: 0.9, sp: 6, vr: 1, li: 1.8, lg: 2, a: 'heal' },
  prayer_of_healing: {
    c: '#ffe9b8',
    p: 'holy',
    pw: 1.05,
    sp: 10,
    rg: 2.4,
    li: 1.8,
    lg: 3,
    wu: 2.5,
    a: 'heal',
  },
  mind_sear: { c: '#7a5f9e', p: 'shadow', pw: 1.15, sp: 18, sm: 1, li: 0.9, lg: 2, a: 'beam' },
  lightning_bolt: {
    c: '#8fd0ff',
    p: 'storm',
    pw: 1.25,
    b: { v: 30, j: 1, co: 1 },
    lg: 3.2,
    wu: 1.7,
    fin: 1,
    a: 'bolt',
  },
  rockbiter_weapon: {
    c: '#b08850',
    p: 'physical',
    pw: 0.75,
    sp: 6,
    rg: 1.2,
    db: 1,
    bo: 'weaponGlow',
    lg: 2.5,
    wu: 0.5,
    a: 'buff',
  },
  healing_wave: { c: '#7fd4ff', p: 'frost', pw: 0.9, sp: 10, vr: 1, li: 1.2, a: 'heal' },
  earth_shock: {
    c: '#dfe6ee',
    p: 'physical',
    pw: 1.05,
    sp: 8,
    rg: 1.3,
    db: 1,
    sm: 1,
    li: 0.7,
    wu: 0.4,
    a: 'burst',
  },
  lightning_shield: { c: '#7fd6ff', p: 'storm', pw: 0.65, bo: 'sparks', lg: 4, wu: 0.4, a: 'buff' },
  flame_shock: { c: '#ff7a2a', p: 'fire', pw: 0.9, sp: 18, sm: 1, li: 0.8, lg: 4, a: 'dot' },
  flametongue_weapon: {
    c: '#ff8c3a',
    p: 'fire',
    pw: 0.75,
    sp: 16,
    sm: 1,
    li: 1.3,
    bo: 'weaponGlow',
    lg: 3,
    a: 'buff',
  },
  frost_shock: {
    c: '#7fd4ff',
    p: 'frost',
    pw: 0.9,
    sp: 0,
    vr: 1,
    db: 1,
    li: 0.8,
    lg: 2.5,
    a: 'burst',
  },
  frostbrand_weapon: {
    c: '#4f9fd8',
    p: 'frost',
    pw: 0.75,
    sp: 0,
    vr: 1,
    db: 1,
    li: 0.9,
    bo: 'weaponGlow',
    lg: 3,
    wu: 0.55,
    a: 'buff',
  },
  ghost_wolf: { c: '#b4a8e0', p: 'moon', pw: 0.6, bo: 'speedlines', lg: 2, a: 'buff' },
  earthquake: {
    c: '#dfe6ee',
    p: 'physical',
    pw: 1.3,
    sp: 6,
    rg: 2,
    db: 1,
    sm: 1,
    li: 0.5,
    lg: 6,
    wu: 0.7,
    a: 'nova',
  },
  chain_heal: {
    c: '#aee7ff',
    p: 'frost',
    pw: 1.35,
    sp: 12,
    vr: 1,
    li: 1.4,
    lg: 2.6,
    wu: 2.4,
    a: 'heal',
  },
  stormstrike: {
    c: '#8fd6ff',
    p: 'storm',
    pw: 1.3,
    sp: 48,
    vr: 1,
    db: 1,
    li: 1.5,
    wu: 0.45,
    a: 'strike',
  },
  elemental_mastery: {
    c: '#a8e6ff',
    p: 'storm',
    pw: 1.1,
    sp: 26,
    vr: 1,
    li: 1.6,
    bo: 'halo',
    lg: 3,
    wu: 0.6,
    a: 'buff',
  },
  healing_stream: { c: '#9fd8c8', p: 'nature', pw: 0.8, sp: 6, li: 1.3, lg: 4, a: 'heal' },
  chain_lightning: {
    c: '#9fd0ff',
    p: 'storm',
    pw: 1.25,
    sp: 34,
    rg: 1.6,
    li: 1.3,
    lg: 2,
    wu: 2.2,
    a: 'burst',
  },
  earthbind: {
    c: '#b89a6a',
    p: 'nature',
    sp: 8,
    rg: 1.8,
    db: 1,
    li: 0.7,
    lg: 2.5,
    wu: 0.3,
    a: 'nova',
  },
  bloodlust: {
    c: '#8fd0ff',
    p: 'storm',
    pw: 1.3,
    sp: 24,
    rg: 2.6,
    vr: 1,
    li: 2.2,
    bo: 'heartbeat',
    lg: 4,
    a: 'buff',
  },
  shadow_bolt: { c: '#8a6ab8', p: 'shadow', sp: 22, sm: 1, b: { v: 21, h: 1.3, co: 1 }, a: 'bolt' },
  summon_imp: { c: '#ff7a2a', p: 'fire', pw: 0.85, sp: 26, sm: 1, li: 1.2, lg: 2, a: 'summon' },
  demon_skin: { c: '#8b3ff5', p: 'shadow', pw: 0.6, bo: 'plates', lg: 3.5, a: 'buff' },
  immolate: { c: '#ff7a2a', p: 'fire', pw: 0.9, sp: 36, sm: 1, lg: 4, a: 'dot' },
  corruption: { c: '#c8ff3c', p: 'venom', pw: 0.85, sp: 6, sm: 1, lg: 4, a: 'dot' },
  life_tap: { c: '#ff4a5a', p: 'blood', pw: 0.65, bl: 1, bo: 'heartbeat', lg: 1.5, a: 'buff' },
  summon_voidwalker: {
    c: '#8a6ab8',
    p: 'shadow',
    pw: 1.1,
    db: 1,
    sm: 1,
    li: 1.2,
    lg: 2.5,
    a: 'summon',
  },
  curse_of_agony: { c: '#8a6ab8', p: 'shadow', pw: 1.05, sp: 10, lg: 4, a: 'dot' },
  drain_life: { c: '#d41f2e', p: 'blood', sp: 12, bl: 1, li: 1.6, lg: 2, a: 'beam' },
  fear: { c: '#8a6ab8', p: 'shadow', pw: 0.85, li: 1.5, lg: 4, a: 'cc' },
  searing_pain: {
    c: '#ffd23e',
    p: 'fire',
    pw: 0.95,
    sp: 44,
    li: 1.4,
    b: { v: 30, h: 0.9 },
    a: 'bolt',
  },
  shadowburn: {
    c: '#8a6ab8',
    p: 'shadow',
    pw: 1.4,
    sp: 50,
    rg: 1,
    vr: 1,
    db: 1,
    sm: 1,
    lg: 2,
    fin: 1,
    a: 'burst',
  },
  summon_infernal: {
    c: '#ff7a2a',
    p: 'fire',
    pw: 1.6,
    sp: 40,
    rg: 2,
    vr: 1,
    db: 1,
    sm: 1,
    li: 2,
    lg: 3,
    wu: 2.4,
    a: 'summon',
  },
  rain_of_fire: {
    c: '#ff7a2a',
    p: 'fire',
    pw: 1.15,
    sp: 30,
    db: 1,
    sm: 1,
    li: 0.9,
    lg: 4,
    wu: 0.4,
    a: 'dot',
  },
  spell_lock: { c: '#8a6ab8', p: 'shadow', pw: 0.75, sp: 20, li: 1.2, a: 'burst' },
  metamorphosis: {
    c: '#8b3ff5',
    p: 'shadow',
    pw: 1.35,
    sp: 22,
    rg: 1.5,
    vr: 1,
    sm: 1,
    li: 1.4,
    bo: 'wings',
    lg: 3,
    wu: 0.7,
    a: 'buff',
  },
  siphon_life: { c: '#ff4a5a', p: 'blood', pw: 1.1, sp: 8, sm: 1, bl: 1, li: 0.5, lg: 4, a: 'dot' },
  conflagrate: {
    c: '#ff7a2a',
    p: 'fire',
    pw: 1.4,
    sp: 50,
    rg: 2,
    vr: 1,
    db: 1,
    sm: 1,
    li: 1.8,
    lg: 2,
    a: 'burst',
  },
  voidfeast: { c: '#8a6ab8', p: 'shadow', pw: 0.95, sp: 10, sm: 1, li: 1.2, lg: 1.5, a: 'burst' },
  howl_of_terror: {
    c: '#5a4a7e',
    p: 'shadow',
    pw: 1.15,
    sp: 0,
    rg: 2,
    sm: 1,
    li: 1.6,
    lg: 2.5,
    wu: 0.3,
    a: 'shout',
  },
  curse_of_exhaustion: {
    c: '#4a4258',
    p: 'shadow',
    pw: 0.7,
    sp: 0,
    sm: 1,
    li: 0.5,
    lg: 4,
    a: 'burst',
  },
  death_coil: {
    c: '#8ae88a',
    p: 'shadow',
    pw: 1.2,
    sp: 18,
    vr: 1,
    sm: 1,
    li: 1.1,
    b: { v: 24, h: 1.2, co: 1 },
    lg: 2,
    a: 'bolt',
  },
  chaos_bolt: {
    c: '#e86aff',
    p: 'fire',
    pw: 1.5,
    sp: 44,
    rg: 1.8,
    vr: 1,
    db: 1,
    sm: 1,
    li: 1.4,
    b: { v: 19, h: 1.5, j: 1, co: 1 },
    lg: 2.5,
    wu: 2.4,
    a: 'bolt',
  },
  wrath: { c: '#8cd07a', p: 'nature', pw: 0.9, li: 0.6, b: { v: 24, co: 1 }, a: 'bolt' },
  healing_touch: { c: '#8cd07a', p: 'nature', a: 'heal' },
  mark_of_the_wild: { c: '#b9d178', p: 'nature', pw: 0.6, bo: 'leaves', lg: 3, a: 'buff' },
  moonfire: { c: '#b4a8e0', p: 'moon', pw: 0.95, sp: 10, li: 0.5, lg: 4, a: 'dot' },
  rejuvenation: { c: '#8cd07a', p: 'nature', pw: 0.65, lg: 4, a: 'heal' },
  thorns: { c: '#3f7a2e', p: 'venom', pw: 0.65, bo: 'sparks', lg: 3.5, a: 'buff' },
  entangling_roots: { c: '#8cd07a', p: 'nature', pw: 0.75, db: 1, sm: 1, li: 0.3, lg: 4, a: 'cc' },
  bear_form: { c: '#9a6a3a', p: 'nature', pw: 0.75, rg: 1.4, db: 1, sm: 1, lg: 2, a: 'buff' },
  bear_charge: { c: '#dfe6ee', p: 'physical', sp: 14, rg: 1.5, db: 1, sm: 1, li: 0.6, a: 'dash' },
  maul: { c: '#dfe6ee', p: 'physical', sp: 10, rg: 1.1, db: 1, li: 0.4, a: 'strike' },
  growl: {
    c: '#ff5f45',
    p: 'physical',
    pw: 1.05,
    sp: 10,
    rg: 2.2,
    vr: 1,
    db: 1,
    sm: 1,
    li: 1.6,
    a: 'shout',
  },
  demoralizing_roar: {
    c: '#7d6b9e',
    p: 'physical',
    pw: 1.1,
    sp: 6,
    rg: 3,
    db: 1,
    sm: 1,
    li: 1.3,
    a: 'shout',
  },
  cat_form: { c: '#8fa3c8', p: 'moon', pw: 0.7, lg: 2, a: 'buff' },
  prowl: { c: '#26303f', p: 'moon', pw: 0.5, lg: 2, a: 'buff' },
  rake: { c: '#d41f2e', p: 'blood', pw: 0.9, sp: 8, bl: 1, li: 0.4, lg: 4, a: 'strike' },
  claw: { c: '#dfe6ee', p: 'physical', pw: 0.85, sp: 8, li: 0.3, a: 'strike' },
  regrowth: { c: '#8cd07a', p: 'nature', pw: 0.9, sp: 12, vr: 1, lg: 3.5, a: 'heal' },
  ferocious_bite: {
    c: '#d41f2e',
    p: 'blood',
    pw: 1.3,
    sp: 30,
    rg: 1.5,
    vr: 1,
    db: 1,
    bl: 1,
    li: 0.5,
    lg: 1.5,
    a: 'strike',
  },
  barkskin: {
    c: '#7a8f66',
    p: 'nature',
    pw: 0.7,
    rg: 1.2,
    db: 1,
    li: 0.5,
    bo: 'plates',
    lg: 4,
    a: 'buff',
  },
  swipe: { c: '#dfe6ee', p: 'physical', pw: 0.85, sp: 18, db: 1, sm: 1, li: 0.5, a: 'nova' },
  starfire: {
    c: '#b4a8e0',
    p: 'moon',
    pw: 1.5,
    sp: 40,
    rg: 1.6,
    vr: 1,
    db: 1,
    sm: 1,
    li: 0.5,
    b: { v: 18, h: 1.7, co: 1 },
    wu: 2.5,
    fin: 1,
    a: 'bolt',
  },
  travel_form: {
    c: '#d9c060',
    p: 'nature',
    pw: 0.6,
    sp: 0,
    sm: 1,
    li: 0.5,
    bo: 'speedlines',
    lg: 2,
    a: 'buff',
  },
  enrage: {
    c: '#d84a2a',
    p: 'blood',
    pw: 0.8,
    sp: 10,
    rg: 1.2,
    db: 1,
    sm: 1,
    li: 0.8,
    bo: 'heartbeat',
    lg: 3,
    wu: 0.3,
    a: 'buff',
  },
  bash: {
    c: '#dfe6ee',
    p: 'physical',
    pw: 0.9,
    sp: 12,
    vr: 1,
    db: 1,
    sm: 1,
    li: 0.5,
    lg: 1.5,
    a: 'strike',
  },
  faerie_fire: {
    c: '#e79aff',
    p: 'nature',
    pw: 0.6,
    sp: 6,
    li: 0.4,
    b: { v: 22, h: 0.7 },
    lg: 4,
    a: 'bolt',
  },
  hibernate: { c: '#cfe8ff', p: 'nature', pw: 0.7, sp: 8, sm: 1, li: 0.4, lg: 4, wu: 1.5, a: 'cc' },
  dash: {
    c: '#6f8fd8',
    p: 'moon',
    pw: 0.7,
    sp: 0,
    sm: 1,
    li: 0.4,
    bo: 'speedlines',
    lg: 3,
    a: 'buff',
  },
  pounce: { c: '#b4a8e0', p: 'moon', pw: 0.95, sp: 6, sm: 1, li: 0.3, lg: 1.5, a: 'strike' },
  insect_swarm: { c: '#b7c94a', p: 'nature', pw: 0.9, sp: 14, li: 0.4, lg: 4, a: 'dot' },
  tigers_fury: {
    c: '#b81f3c',
    p: 'blood',
    pw: 0.9,
    sp: 10,
    bl: 1,
    li: 0.7,
    bo: 'heartbeat',
    lg: 3,
    a: 'buff',
  },
  rip: { c: '#d41f2e', p: 'blood', pw: 1.1, sp: 8, vr: 1, bl: 1, li: 0.5, lg: 4, a: 'dot' },
  hurricane: {
    c: '#b6c0a8',
    p: 'storm',
    pw: 1.2,
    sp: 22,
    rg: 2,
    db: 1,
    sm: 1,
    li: 1.1,
    lg: 6,
    wu: 0.6,
    a: 'nova',
  },
  skull_bash: {
    c: '#dfe6ee',
    p: 'physical',
    pw: 0.75,
    sp: 0,
    vr: 1,
    db: 1,
    sm: 1,
    li: 0.6,
    a: 'strike',
  },
  primal_reflexes: {
    c: '#4fd9a6',
    p: 'nature',
    pw: 0.85,
    sp: 8,
    li: 0.6,
    bo: 'wings',
    lg: 4,
    a: 'buff',
  },
  moonkin_form: {
    c: '#c9a6ff',
    p: 'moon',
    pw: 1.2,
    sp: 26,
    rg: 1.6,
    db: 1,
    sm: 1,
    li: 1.4,
    bo: 'halo',
    lg: 2.5,
    wu: 0.5,
    a: 'buff',
  },
  feral_charge: {
    c: '#e0341f',
    p: 'blood',
    pw: 1.3,
    sp: 26,
    rg: 1.4,
    vr: 1,
    db: 1,
    sm: 1,
    li: 1.2,
    bo: 'sparks',
    lg: 3.5,
    wu: 0.3,
    a: 'buff',
  },
  swiftmend: { c: '#8fe86a', p: 'nature', pw: 1.1, sp: 20, vr: 1, li: 1.5, lg: 2, a: 'heal' },
  typhoon: {
    c: '#6fc8e8',
    p: 'nature',
    pw: 1.15,
    sp: 0,
    rg: 2.8,
    db: 1,
    sm: 1,
    li: 0.9,
    lg: 1.5,
    wu: 0.3,
    a: 'nova',
  },
  innervate: {
    c: '#a8e890',
    p: 'nature',
    pw: 0.85,
    sp: 10,
    li: 1.2,
    bo: 'runes',
    lg: 4,
    a: 'buff',
  },
  frenzied_regeneration: { c: '#c86a4a', p: 'nature', pw: 0.85, sp: 4, li: 1.2, lg: 4, a: 'heal' },
  berserk: {
    c: '#d42a1e',
    p: 'blood',
    pw: 1.15,
    sp: 20,
    bl: 1,
    li: 1.2,
    bo: 'weaponGlow',
    lg: 4,
    wu: 0.25,
    a: 'buff',
  },
  tranquility: {
    c: '#bfe8a8',
    p: 'nature',
    pw: 1.15,
    sp: 8,
    rg: 2.6,
    li: 2,
    lg: 4,
    wu: 2.5,
    a: 'heal',
  },
};
