import type { AbilityVfxFullSpec, AbilityVfxSpec } from './ability_vfx_core';

// Gloom Bolt borrows Ruinbolt's satisfying contact vocabulary, but stays a
// compact rotational filler: a thin green shadow-fang, short wake, restrained
// layered hit, no screen flash, and no finisher crescendo.
export const GLOOM_BOLT_VFX_SPEC = {
  c: '#48f06f',
  p: 'venom',
  pw: 0.9,
  sp: 26,
  rg: 0.8,
  vr: 1,
  db: 1,
  sm: 1,
  li: 0.95,
  b: { v: 26, h: 0.95, co: 1 },
  lg: 0.65,
  wu: 1.7,
  a: 'bolt',
} satisfies AbilityVfxSpec;

export const GLOOM_BOLT_VFX_FULL_SPEC = {
  archetype: 'bolt',
  palette: 'venom',
  tint: '#48f06f',
  power: 0.9,
  filler: true,
  chargeStreams: 2,
  bolt: {
    speed: 26,
    headScale: 0.95,
    style: 'shadowFang',
    core: '#06170c',
    accent: '#c5ff86',
    coils: true,
  },
  windup: 1.7,
  windupStyle: 'compression',
  linger: 0.65,
  decal: 'scorch',
  rim: '#c5ff86',
  screenFx: false,
  impact: {
    focused: true,
    flipbook: true,
    ring: 0.8,
    vRing: true,
    sparks: 26,
    debris: true,
    smoke: true,
    light: 0.95,
    liteAudio: true,
  },
} satisfies AbilityVfxFullSpec;

// Destruction-owned override for the existing Ruinbolt. The large
// ability_vfx_*_specs tables are generated projections of the external VFX
// gallery; keeping this bespoke spell here prevents a future gallery
// regeneration from silently replacing its three-Ruin visual identity.
export const RUINBOLT_VFX_SPEC = {
  c: '#72ff38',
  p: 'venom',
  pw: 1.65,
  sp: 52,
  rg: 1.25,
  vr: 1,
  db: 1,
  sm: 1,
  li: 1.7,
  b: { v: 26, h: 1.65, j: 1, co: 1 },
  lg: 2.8,
  wu: 2.5,
  a: 'bolt',
} satisfies AbilityVfxSpec;

export const RUINBOLT_VFX_FULL_SPEC = {
  archetype: 'bolt',
  palette: 'venom',
  tint: '#72ff38',
  power: 1.65,
  chargeStreams: 3,
  bolt: {
    speed: 26,
    headScale: 1.65,
    style: 'felLance',
    jagged: true,
    coils: true,
    forkEvery: 0.1,
  },
  windup: 2.5,
  windupStyle: 'vortex',
  hot: 0.1,
  linger: 2.8,
  decal: 'scorch',
  rim: '#d8ff58',
  impact: {
    focused: true,
    flipbook: true,
    ring: 1.25,
    vRing: true,
    sparks: 52,
    debris: true,
    smoke: true,
    light: 1.7,
    sample: 'imp_chaos',
  },
} satisfies AbilityVfxFullSpec;

// Powerful VFX: fel-green fire coils around the victim for the full pact,
// with five falling ember knots that make the remaining periodic stages read.
export const BURNING_PACT_VFX_SPEC = {
  c: '#58f044',
  p: 'venom',
  pw: 1.12,
  sp: 30,
  rg: 0.9,
  vr: 1,
  db: 1,
  sm: 1,
  li: 1.1,
  b: { v: 25, h: 1.05, co: 1 },
  bo: 'sparks',
  lg: 2.1,
  wu: 2,
  a: 'bolt',
} satisfies AbilityVfxSpec;

export const BURNING_PACT_VFX_FULL_SPEC = {
  archetype: 'bolt',
  palette: 'venom',
  tint: '#58f044',
  accent: '#ffb43d',
  rim: '#d8ff74',
  power: 1.12,
  chargeStreams: 2,
  windup: 2,
  windupStyle: 'compression',
  bolt: {
    speed: 25,
    headScale: 1.05,
    style: 'felLance',
    core: '#0a1d0b',
    accent: '#ffb43d',
    coils: true,
    jagged: false,
    forkEvery: 0,
    tracer: true,
  },
  dot: { drip: 'fall' },
  debuff: {
    orbit: 'sparks',
    o: { n: 5, size: 0.25, rate: 0.7, weave: 0.08, radius: 0.88, incline: 0.22 },
  },
  decal: 'scorch',
  linger: 2.1,
  impact: {
    focused: true,
    flipbook: true,
    ring: 0.9,
    vRing: 0.65,
    sparks: 30,
    debris: true,
    smoke: true,
    light: 1.1,
    sample: 'imp_fire',
  },
} satisfies AbilityVfxFullSpec;

// Powerful VFX: Conflagrate tears one ember knot out of Burning Pact and
// drives it back into the victim as a compact, two-stream fel detonation.
export const CONFLAGRATE_VFX_SPEC = {
  c: '#83ff3f',
  p: 'venom',
  pw: 1.32,
  sp: 40,
  rg: 1.1,
  vr: 1,
  db: 1,
  sm: 1,
  li: 1.4,
  b: { v: 34, h: 1.3, j: 1, co: 1 },
  lg: 2.3,
  wu: 0.08,
  fin: 1,
  a: 'bolt',
} satisfies AbilityVfxSpec;

export const CONFLAGRATE_VFX_FULL_SPEC = {
  archetype: 'bolt',
  palette: 'venom',
  tint: '#83ff3f',
  accent: '#ffc044',
  rim: '#edff8b',
  hot: 0.08,
  power: 1.32,
  finisher: true,
  chargeStreams: 2,
  windup: 0.08,
  windupStyle: 'vortex',
  motifs: ['implosion'],
  motifAt: 'target',
  bolt: {
    speed: 34,
    headScale: 1.3,
    style: 'felLance',
    core: '#10250b',
    accent: '#ffc044',
    coils: true,
    jagged: true,
    forkEvery: 0.16,
    tracer: true,
  },
  decal: 'scorch',
  linger: 2.3,
  impact: {
    focused: true,
    flipbook: true,
    ring: 1.1,
    vRing: 0.85,
    sparks: 40,
    debris: true,
    smoke: true,
    light: 1.4,
    sample: 'imp_chaos',
  },
} satisfies AbilityVfxFullSpec;

export const DUSKFIRE_VFX_SPEC = {
  c: '#6df54a',
  p: 'shadow',
  pw: 1.42,
  sp: 44,
  rg: 1.18,
  vr: 1,
  db: 1,
  sm: 1,
  li: 1.45,
  b: { v: 31, h: 1.4, j: 1, co: 1 },
  lg: 2.6,
  wu: 0.06,
  fin: 1,
  a: 'bolt',
} satisfies AbilityVfxSpec;

export const DUSKFIRE_VFX_FULL_SPEC = {
  archetype: 'bolt',
  palette: 'shadow',
  tint: '#6df54a',
  accent: '#a160de',
  rim: '#dcff8d',
  hot: 0.08,
  power: 1.42,
  finisher: true,
  windup: 0.06,
  windupStyle: 'compression',
  motifs: ['claws', 'implosion'],
  motifAt: 'target',
  bolt: {
    speed: 31,
    headScale: 1.4,
    style: 'shadowFang',
    core: '#170a25',
    accent: '#6df54a',
    coils: true,
    jagged: true,
    forkEvery: 0.14,
    tracer: true,
  },
  decal: 'scorch',
  screenFx: true,
  linger: 2.6,
  impact: {
    focused: true,
    flipbook: true,
    ring: 1.18,
    vRing: 0.9,
    sparks: 44,
    debris: true,
    smoke: true,
    light: 1.45,
    sample: 'imp_shadow',
  },
} satisfies AbilityVfxFullSpec;

export const RUINOUS_BRAND_VFX_SPEC = {
  c: '#75f23d',
  p: 'venom',
  pw: 1.2,
  sp: 34,
  rg: 1,
  vr: 1,
  sm: 1,
  li: 1.2,
  bo: 'runes',
  lg: 2.4,
  wu: 0.12,
  a: 'cc',
} satisfies AbilityVfxSpec;

export const RUINOUS_BRAND_VFX_FULL_SPEC = {
  archetype: 'cc',
  palette: 'venom',
  tint: '#75f23d',
  accent: '#bd6cff',
  rim: '#e2ff82',
  power: 1.2,
  windup: 0.12,
  windupStyle: 'runes',
  motifs: ['chains'],
  motifAt: 'target',
  debuff: {
    orbit: 'runes',
    o: { n: 3, size: 0.34, rate: 0.52, weave: 0.04, radius: 1, incline: 0.16 },
  },
  decal: 'rune',
  linger: 2.4,
  impact: {
    focused: true,
    flipbook: false,
    ring: 1,
    vRing: 0.72,
    sparks: 34,
    debris: false,
    smoke: true,
    light: 1.2,
    sample: 'imp_chaos',
  },
} satisfies AbilityVfxFullSpec;

export const RAIN_OF_FIRE_VFX_SPEC = {
  c: '#78f33c',
  p: 'venom',
  pw: 1.58,
  sp: 50,
  rg: 1.7,
  vr: 1,
  db: 1,
  sm: 1,
  li: 1.65,
  lg: 5.8,
  wu: 0.12,
  fin: 1,
  a: 'nova',
} satisfies AbilityVfxSpec;

export const RAIN_OF_FIRE_VFX_FULL_SPEC = {
  archetype: 'nova',
  palette: 'venom',
  tint: '#78f33c',
  accent: '#ff9e32',
  rim: '#e8ff70',
  hot: 0.1,
  power: 1.58,
  finisher: true,
  windup: 0.12,
  windupStyle: 'vortex',
  motifs: ['pillars', 'fissure'],
  motifAt: 'target',
  motifEvery: 0.7,
  motifR: 7,
  nova: { radius: 7 },
  decal: 'scorch',
  screenFx: true,
  linger: 5.8,
  impact: {
    flipbook: true,
    ring: 1.7,
    vRing: 1.25,
    sparks: 50,
    debris: true,
    smoke: true,
    light: 1.65,
    sample: 'imp_chaos',
  },
} satisfies AbilityVfxFullSpec;

export const PYRE_COLOSSUS_VFX_SPEC = {
  c: '#82ff45',
  p: 'venom',
  pw: 1.72,
  sp: 56,
  rg: 1.8,
  vr: 1,
  db: 1,
  sm: 1,
  li: 1.8,
  lg: 3.5,
  wu: 2,
  fin: 1,
  a: 'summon',
} satisfies AbilityVfxSpec;

export const PYRE_COLOSSUS_VFX_FULL_SPEC = {
  archetype: 'summon',
  palette: 'venom',
  tint: '#82ff45',
  accent: '#ff9d35',
  rim: '#efff84',
  hot: 0.08,
  power: 1.72,
  finisher: true,
  windup: 2,
  windupStyle: 'ascend',
  motifs: ['pillars', 'fissure', 'implosion'],
  motifAt: 'target',
  nova: { radius: 6 },
  decal: 'scorch',
  screenFx: true,
  linger: 3.5,
  impact: {
    flipbook: true,
    ring: 1.8,
    vRing: 1.35,
    sparks: 56,
    debris: true,
    smoke: true,
    light: 1.8,
    sample: 'imp_chaos',
  },
} satisfies AbilityVfxFullSpec;
